### PR TITLE
IN: bills and events scraper rewrite 2025

### PR DESCRIPTION
**Pull request by braykuka**
- Fix the text format issue in vote pdf scraping
- [1240](https://github.com/openstates/issues/issues/1240)
- [1207](https://github.com/openstates/issues/issues/1207)

### CODE REVIEW

**Comment by braykuka** [comment]
@jessemortenson Please review it.

**Comment by jessemortenson** [comment]
Thanks, Bray. I just ran this one and got the following error, can you please check it?

```
/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/bin/python -m openstates.cli.update --scrape --fastmode in bills 
11:07:08 DEBUG openstates.stats: Stat emission is not enabled.
11:07:08 INFO root: Module: in
in (scrape)
  bills: {}
11:07:13 INFO openstates: save jurisdiction Indiana as jurisdiction_ocd-jurisdiction-country:us-state:in-government.json
11:07:13 INFO openstates: save organization Indiana General Assembly as organization_13beff08-954f-11ef-ad10-4c034f4dc15f.json
11:07:13 INFO openstates: save organization Senate as organization_13beff09-954f-11ef-ad10-4c034f4dc15f.json
11:07:13 INFO openstates: save organization House as organization_13beff0a-954f-11ef-ad10-4c034f4dc15f.json
11:07:13 WARNING openstates: no session provided, using active sessions: {'2024'}

...

11:13:22 INFO openstates: save bill HB 1429 in 2024 as bill_ef4cc848-954f-11ef-ad10-4c034f4dc15f.json
11:13:22 INFO openstates: Api GET: 'https://beta-api.iga.in.gov/2024/bills/hb1430', (), {'headers': {'x-api-key': '...', 'Accept': 'application/json', 'User-Agent': 'openstates'}}
11:13:22 INFO scrapelib: GET - 'https://beta-api.iga.in.gov/2024/bills/hb1430'
11:13:22 INFO openstates: Api GET: 'https://beta-api.iga.in.gov/2024/bills/hb1430/actions', (), {'headers': {'x-api-key': '...', 'Accept': 'application/json', 'User-Agent': 'openstates'}}
11:13:22 INFO scrapelib: GET - 'https://beta-api.iga.in.gov/2024/bills/hb1430/actions'
11:13:22 INFO openstates: save bill HB 1430 in 2024 as bill_ef4cc849-954f-11ef-ad10-4c034f4dc15f.jsona
11:13:22 INFO openstates: Api GET: 'https://beta-api.iga.in.gov/2024/bills/hb1431', (), {'headers': {'x-api-key': '...', 'Accept': 'application/json', 'User-Agent': 'openstates'}}
11:13:22 INFO scrapelib: GET - 'https://beta-api.iga.in.gov/2024/bills/hb1431'
Traceback (most recent call last):
  File "/home/jesse/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jesse/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 610, in <module>
    sys.exit(main())
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 600, in main
    report = do_update(args, other, juris)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 389, in do_update
    report["scrape"] = do_scrape(juris, args, scrapers, active_sessions)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 133, in do_scrape
    partial_report = scraper.do_scrape(**scrape_args, session=session)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/scrape/base.py", line 236, in do_scrape
    for obj in self.scrape(**kwargs) or []:
  File "/home/jesse/repo/openstates/braykuka/openstates-scrapers/scrapers/in/bills.py", line 336, in scrape
    title = bill_json["description"]
KeyError: 'description'
```

**Comment by jessemortenson** [comment]
Looking at the Events scraper, noticing a few things:

- I pushed a commit to this branch that fixes an error that would be thrown on all day events
- There are some 404 URLs in the sources array, but it looks like they might be bad in the source data itself. These URLs have a double slash in them (`https://iga.in.gov/2024/committees//legislative-council`, whereas the `committee.link` property in the source API response does not have that double slash (`/2024/committees/committee_i_legislative_council`). Nonetheless, the URLs do not work (404 response) with or without the double slash. So that's weird, but I'm not sure if there's anything you can do to fix it.

```
D SELECT start_date, s.url, so.url FROM events e LEFT JOIN event_sources s ON e._id = s.event_id AND s.note = 'Committee Schedule' LEFT JOIN event_sources so ON e._id = so.event_id AND so.note != 'Committee Schedule' WHERE s.url LIKE '%committees//%';
┌───────────────────────────┬────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────┐
│        start_date         │                                        url                                         │                                      url                                       │
├───────────────────────────┼────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────┤
│ 2024-09-26T14:00:00+00:00 │ https://iga.in.gov/2024/committees//courts-and-the-judiciary,-interim-study-com... │ https://beta-api.iga.in.gov/2024/meetings/149c448d-a2cd-46d2-8150-55b60ccee5b7 │
│ 2024-09-10T15:00:00+00:00 │ https://iga.in.gov/2024/committees//corrections-and-criminal-code,-interim-stud... │ https://beta-api.iga.in.gov/2024/meetings/bf14bd1f-9e7e-4a2d-9855-613316d9277e │
│ 2024-08-27T13:00:00+00:00 │ https://iga.in.gov/2024/committees//medicaid-oversight-committee                   │ https://beta-api.iga.in.gov/2024/meetings/af366af1-30ca-4e86-9a8f-b2a5ee6a469d │
│ 2024-10-15T14:00:00+00:00 │ https://iga.in.gov/2024/committees//fiscal-policy,-interim-study-committee-on      │ https://beta-api.iga.in.gov/2024/meetings/71af7122-9b85-460b-978b-be042b48b8a2 │
│ 2024-09-23T17:00:00+00:00 │ https://iga.in.gov/2024/committees//pension-management-oversight,-interim-study... │ https://beta-api.iga.in.gov/2024/meetings/df1515c9-85de-4463-815b-78b08e3acac1 │
│ 2024-10-25T13:00:00+00:00 │ https://iga.in.gov/2024/committees//education,-interim-study-committee-on          │ https://beta-api.iga.in.gov/2024/meetings/0a2918c2-fc4b-4e68-963c-f1c0b99de494 │
│ 2024-09-09T17:30:00+00:00 │ https://iga.in.gov/2024/committees//government,-interim-study-committee-on         │ https://beta-api.iga.in.gov/2024/meetings/541c1c48-8305-44c3-8d81-f05bf6f25097 │
│ 2024-09-18T14:00:00+00:00 │ https://iga.in.gov/2024/committees//child-services,-interim-study-committee-on     │ https://beta-api.iga.in.gov/2024/meetings/7e2c74c0-2d6a-44e8-8565-f59672226fa7 │
│ 2024-10-21T17:30:00+00:00 │ https://iga.in.gov/2024/committees//government,-interim-study-committee-on         │ https://beta-api.iga.in.gov/2024/meetings/d47ded80-467a-4cc3-8a25-defa003a7121 │
│ 2024-10-28T17:00:00+00:00 │ https://iga.in.gov/2024/committees//pension-management-oversight,-interim-study... │ https://beta-api.iga.in.gov/2024/meetings/08b08863-86ac-49f9-9e7a-920c294d823c │
│ 2024-10-03T14:00:00+00:00 │ https://iga.in.gov/2024/committees//courts-and-the-judiciary,-interim-study-com... │ https://beta-api.iga.in.gov/2024/meetings/65644c8c-4d78-4a8a-a643-78aa577581bb │
│ 2024-08-28T17:30:00+00:00 │ https://iga.in.gov/2024/committees//government,-interim-study-committee-on         │ https://beta-api.iga.in.gov/2024/meetings/84f1aac3-718e-4a1b-a9bd-9317ce61fef4 │
│ 2024-10-08T17:00:00+00:00 │ https://iga.in.gov/2024/committees//health-care-cost-oversight-task-force          │ https://beta-api.iga.in.gov/2024/meetings/d5eacf9a-242e-4faf-b7df-b31e448ffe96 │
│ 2024-08-21T18:00:00+00:00 │ https://iga.in.gov/2024/committees//artificial-intelligence-task-force             │ https://beta-api.iga.in.gov/2024/meetings/13d71e04-f852-4f94-85e5-23f6dacfc10d │
│ 2024-10-10T14:00:00+00:00 │ https://iga.in.gov/2024/committees//artificial-intelligence-task-force             │ https://beta-api.iga.in.gov/2024/meetings/72d23c09-91a1-4b6b-a12f-57cdf7fb20f0 │
│ 2024-06-18T14:00:00+00:00 │ https://iga.in.gov/2024/committees//state-and-local-tax-review-task-force          │ https://beta-api.iga.in.gov/2024/meetings/697680b3-1039-43e1-90fe-83118494afef │
│ 2024-10-23T17:00:00+00:00 │ https://iga.in.gov/2024/committees//state-fair-advisory-committee                  │ https://beta-api.iga.in.gov/2024/meetings/cacc6569-2433-43c3-8a72-633299c6e0c7 │
│ 2024-10-01T14:00:00+00:00 │ https://iga.in.gov/2024/committees//probate-code-study-committee                   │ https://beta-api.iga.in.gov/2024/meetings/fd888e1d-dd8d-4544-bf6a-aa8484ebba6b │
│ 2024-05-14T18:00:00+00:00 │ https://iga.in.gov/2024/committees//legislative-council                            │ https://beta-api.iga.in.gov/2024/meetings/3e5766a8-dbfc-42d3-b3d6-c9bc413bd1bd │
│ 2024-09-26T14:00:00+00:00 │ https://iga.in.gov/2024/committees//roads-and-transportation,-interim-study-com... │ https://beta-api.iga.in.gov/2024/meetings/c129c84a-45ef-43dd-bcc3-638c9ca85267 │
│ 2024-08-27T17:00:00+00:00 │ https://iga.in.gov/2024/committees//funding-indiana's-roads-for-a-stronger,-saf... │ https://beta-api.iga.in.gov/2024/meetings/e806c4d7-bc45-4af0-a5ae-3ae4d9f6ac5a │
│ 2024-10-24T14:00:00+00:00 │ https://iga.in.gov/2024/committees//energy,-utilities,-and-telecommunications,-... │ https://beta-api.iga.in.gov/2024/meetings/f05aaff1-3671-4568-8801-961e99cbfea8 │
│ 2024-09-24T14:00:00+00:00 │ https://iga.in.gov/2024/committees//code-revision-committee                        │ https://beta-api.iga.in.gov/2024/meetings/066e2486-2359-4526-b0db-f3be6971b392 │
│ 2024-10-29T17:00:00+00:00 │ https://iga.in.gov/2024/committees//health-care-cost-oversight-task-force          │ https://beta-api.iga.in.gov/2024/meetings/949e9039-5f51-4477-84cc-96e396865959 │
│ 2024-09-26T14:00:00+00:00 │ https://iga.in.gov/2024/committees//education,-interim-study-committee-on          │ https://beta-api.iga.in.gov/2024/meetings/18e4d994-7cc5-46c8-812d-575bb41ccc68 │
│ 2024-09-05T17:30:00+00:00 │ https://iga.in.gov/2024/committees//roads-and-transportation,-interim-study-com... │ https://beta-api.iga.in.gov/2024/meetings/9cc9bfc2-4cef-4a1a-974c-d6c8d36503e0 │
│ 2024-09-17T14:00:00+00:00 │ https://iga.in.gov/2024/committees//legislative-council,-audit-and-financial-re... │ https://beta-api.iga.in.gov/2024/meetings/68aaaa3b-c78f-486b-80aa-e09fe8294f37 │
└───────────────────────────┴────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────┘
```

* I think there is more data we can grab from this API that will be useful, since we're looking at it now. Looking at `https://beta-api.iga.in.gov/2024/meetings/3e5766a8-dbfc-42d3-b3d6-c9bc413bd1bd` for example, I see a few things:
    * There is an `agenda` property with 5 items. Each of those will be best to be captured as an agenda item on the event. Currently the scraped output shows a single agenda item labeled "Bills under consideration", without any  related bills. Having the 5 items from the `agenda` property would be better. On events that DO have `bill` items in the `agenda` property: the way you are handling these cases by bundling them under `Bills under consideration` is OK. So basically: don't need to change the logic for handling bills agenda items, but please change to incorporate other agenda items as well.
    * There is a property called `exhibits` and another property called `minutes`. If there are items in these properties, please capture them ad Documents on the event. Currently none of the Events in the scraped output have Documents.
* Please trim the leading zeros on related bills, so for instance I see a related bill in the output `SB 0029` - this should instead be `SB 29`

Still looking a bit so might have more feedback later

**Comment by braykuka** [comment]
@jessemortenson Thanks for your review. I will check and fix it.

**Comment by jessemortenson** [comment]
Thanks! Additional requests re: the Events scraper:

- The source has a convention for some of these event/committee names that looks like `Pension Management Oversight, Interim Study Committee on` or `Education, Interim Study Committee on`. Can you please reformat these (and similar "Interim Study" names)  to `Pension Management Oversight Interim Study` and `Education Interim Study`? 
- Directly related to that, please make that same change to the Committee name that is added as a Participant to the event (the participating Committee's name should also be `Pension Management Oversight Interim Study` etc.)
- Unfortunately it looks like there is an event agenda document that is not included in the API output, and is only linked from the event web page. It would be great to capture this as a Document, but I'm not sure if it's possible. If you think there's a reliable way to do it, that would be great. On the event webpage there is a "pdf" button, which for recent events goes to a PDF document showing the event agenda. Examples:
    - [Pension oversight](https://iga.in.gov/2024/committees/interim/pension-management-oversight-interim-study-committee?meeting_lpid=08b08863-86ac-49f9-9e7a-920c294d823c) agenda URL is: https://iga.in.gov/pdf-documents/123/2024/universal/committees/interim/pension-management-oversight-interim-study-committee/08b08863-86ac-49f9-9e7a-920c294d823c/meeting.pdf
    - [Health Care Cost Oversight](https://iga.in.gov/2024/committees/interim/health-care-cost-oversight-task-force?meeting_lpid=949e9039-5f51-4477-84cc-96e396865959) agenda URL is: https://iga.in.gov/pdf-documents/123/2024/universal/committees/interim/health-care-cost-oversight-task-force/949e9039-5f51-4477-84cc-96e396865959/meeting.pdf

**Comment by braykuka** [comment]
@jessemortenson, I've fixed and fully tested for 2 scrapers. Please review them and let me know issues.

**Comment by jessemortenson** [comment]
Thank you! Just checked the Events scraper and looks good to me. I pushed a small commit to fix a typo, add a couple comments, and removed a line of code that didn't do anything. Will be looking at Bills next ...

**Comment by jessemortenson** [comment]
Bill scraper looks good too, merging in.

**Pull request merged**
