### PR TITLE
CT: fix vote scraping logic

### PR DESCRIPTION
**Pull request by braykuka**
## Description

I've added the new scraping logic for vote.

### CODE REVIEW

**Comment by braykuka** [comment]
@jessemortenson Please review it.

**Comment by jessemortenson** [comment]
Code itself looks good, but I can't get this job to run all the way through. I keep getting a connection timeout. Are you experiencing this? If not, what command are you using to run the scraper?

Here's what I tried:

```
/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/bin/python -m openstates.cli.update --scrape ct votes session=2023 
16:11:21 DEBUG openstates.stats: Stat emission is not enabled.
16:11:21 INFO root: Module: ct
ct (scrape)
  votes: {'session': '2023'}
16:11:22 INFO openstates: save jurisdiction Connecticut as jurisdiction_ocd-jurisdiction-country:us-state:ct-government.json
16:11:22 INFO openstates: save organization Connecticut General Assembly as organization_5c24cac4-ac17-11ee-9eb7-0b84faa3af16.json
16:11:22 INFO openstates: save organization Senate as organization_5c24cac5-ac17-11ee-9eb7-0b84faa3af16.json
16:11:22 INFO openstates: save organization House as organization_5c24cac6-ac17-11ee-9eb7-0b84faa3af16.json
/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py:101: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  "session" in inspect.getargspec(ScraperCls.scrape).args
16:11:23 INFO openstates: save vote_event 2023 - 2023-01-25 - Senate Roll Call Vote as vote_event_5c24cac7-ac17-11ee-9eb7-0b84faa3af16.json
16:11:23 INFO openstates: save vote_event 2023 - 2023-01-25 - Senate Roll Call Vote as vote_event_5c24cac8-ac17-11ee-9eb7-0b84faa3af16.json
... [many more vote event lines omitted] ...
16:11:57 INFO openstates: save vote_event 2023 - 2023-05-11 - Senate Roll Call Vote as vote_event_701b23da-ac17-11ee-9eb7-0b84faa3af16.json
16:11:57 INFO openstates: save vote_event 2023 - 2023-05-11 - Senate Roll Call Vote as vote_event_701b23db-ac17-11ee-9eb7-0b84faa3af16.json
16:11:57 INFO openstates: save vote_event 2023 - 2023-05-11 - Senate Roll Call Vote as vote_event_701b23dc-ac17-11ee-9eb7-0b84faa3af16.json
Traceback (most recent call last):
  File "/home/jesse/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jesse/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 551, in <module>
    sys.exit(main())
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 541, in main
    report = do_update(args, other, juris)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 337, in do_update
    report["scrape"] = do_scrape(juris, args, scrapers, active_sessions)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 156, in do_scrape
    report[scraper_name] = scraper.do_scrape(**scrape_args)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/scrape/base.py", line 233, in do_scrape
    for obj in self.scrape(**kwargs) or []:
  File "/home/jesse/repo/openstates/braykuka/openstates-scrapers/scrapers/ct/votes.py", line 19, in scrape
    yield from self.scrape_votes(session, chambers)
  File "/home/jesse/repo/openstates/braykuka/openstates-scrapers/scrapers/ct/votes.py", line 38, in scrape_votes
    ftp.retrbinary(f"RETR {ftp_uri}{file_name}", r.write)
  File "/home/jesse/.pyenv/versions/3.9.13/lib/python3.9/ftplib.py", line 436, in retrbinary
    with self.transfercmd(cmd, rest) as conn:
  File "/home/jesse/.pyenv/versions/3.9.13/lib/python3.9/ftplib.py", line 393, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/home/jesse/.pyenv/versions/3.9.13/lib/python3.9/ftplib.py", line 354, in ntransfercmd
    conn = socket.create_connection((host, port), self.timeout,
  File "/home/jesse/.pyenv/versions/3.9.13/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/home/jesse/.pyenv/versions/3.9.13/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

Process finished with exit code 1
```

**Comment by jessemortenson** [comment]
I spot checked a handful of the Vote Events in output, and those all looked good. So if we can resolve this connection timeout issue I described above, then I think this work is done

**Comment by braykuka** [comment]
@jessemortenson I guess this seems to happen by fast FTP requests. so I've updated it to http requests. Please review it again.

**Comment by jessemortenson** [comment]
Thanks! I was able to run the votes scraper to its end. Let's consider this one complete! 

Not merging until we have 2024 bills posted ... basically waiting on https://github.com/openstates/openstates-scrapers/pull/4766

**Comment by showerst** [comment]
@jessemortenson ping that I merged the bills scraper, not sure if there are votes posted yet.

**Pull request merged**
