### PR TITLE
Co people spatula

### PR DESCRIPTION
**Pull request by morden35**
Writing Colorado people scraper using spatula framework. All Senators and Representatives have 200 E Colfax RM 307 Denver, CO 80203 or 200 E Colfax RM 346 Denver, CO 80203 or 200 E Colfax RM 272 Denver, CO 80203 as their 'mailing address'. I am currently assigning this to their capitol office address (see line 33). There are no district office addresses listed. @jamesturk

### CODE REVIEW

**Comment by morden35** [comment]
I see in the old code that their is an 'UPPER_ADDRESS' and 'LOWER_ADDRESS'. So I guess all senators have the same address and all reps have the same address.

**Comment by jamesturk** [comment]
this looks good to me! could you merge the latest main in so that the conflict message w/ IL is resolved?

**Comment by morden35** [comment]
@jamesturk okay I think latest main should be merged now.

**Comment by jamesturk** [comment]
something went wrong there, the latest PR deletes the IL scraper 

it may be best to:
- pull from main
- create a new branch
- use git cherry-pick to get the relevant commits onto the new branch
- replace this PR with that one

**Pull request closed without merging**
