### PR TITLE
CA: New events scraper that targets websites

### PR DESCRIPTION
**Pull request by braykuka**

### CODE REVIEW

**Comment by braykuka** [comment]
@jessemortenson Please review it.

**Comment by jessemortenson** [comment]
Finally getting back to this! This looks like a good start but I think there are a few areas I'd like you to improve:

# Assembly events

## missing some Assembly events

There are some events that I don't see in the scraper output. For example there is a "BUDGET SUBCOMMITTEE NO. 6 ON PUBLIC SAFETY" event on February 26, but it doesn't appear in the JSON output from the scraper. That event recurs on several days in addition to Feb 26: March 4, March 11, March 18, April 8, May 13, May 20. But the JSON output from the scraper only includes two instances: the ones on May 13 and 20th.

I think I saw other recurring events where some instances were missing, as well.

```
jesse@greenbookwork:~/repo/openstates/braykuka/openstates-scrapers/_data/ca$ for x in `rg -ci 'BUDGET SUBCOMMITTEE NO. 6 ON PUBLIC SAFETY' event_*`; do cat `echo "$x" | awk -F':' '{print $1}'` | jq .name,.start_date; done
"BUDGET SUBCOMMITTEE NO. 6 ON PUBLIC SAFETY"
"2024-05-20T21:30:00+00:00"
"BUDGET SUBCOMMITTEE NO. 6 ON PUBLIC SAFETY"
"2024-05-13T21:30:00+00:00"
```

## Agenda items: events with only a "SUBJECT"

A lot of the events from [the Assembly](https://www.assembly.ca.gov/schedules-publications/assembly-daily-file) are scraped to have an agenda item called simply "INFORMATIONAL HEARING." However on the website there is often a more specific topic. For example on the Feb 13 "JOINT HEARING PRIVACY...." event, the agenda also includes "SUBJECT: Online Ticketing and Access to Live Entertainment." In this case, it would be more useful for the agenda item (`.agenda[].description`) to be titled "Online Ticketing and Access to Live Entertainment" - screenshot:

image

## Agenda items: events with a "SUBJECT" and additional items

Another event on Feb 13, "JOINT HEARING BUDGET SUBCOMMITTE NO. 5 ..." has an agenda that includes both "SUBJECT: Overview of the State Small Business Credit Initiative (SSBCI)." and two other items: "0509 Governor's Office of Business and Economic Development (Go-Biz)" and "0950 Treasurer's Office." I think the agenda items for this kind of event should be a list of three things: "Overview of the State Small Business Credit Initiative (SSBCI)", "Governor's Office of Business and Economic Development (Go-Biz)" and "Treasurer's Office" - screenshot:

image

## Agenda items: events that list "Committees:"

Both of the events I mention above also show a list of Committees. The first links to [Arts, Entertainment, Sports, and Tourism](https://aart.assembly.ca.gov/) and [Privacy and Consumer Protection](https://apcp.assembly.ca.gov/). For an event that has Committees listed, as well as agenda items, it would be beneficial to add related entities to represent those committees. So each agenda item for Feb 13 "JOINT HEARING PRIVACY...." event would have two related entities with the `entity_name` of `Assembly Jobs, Economic Development, and the Economy Committee` and `Assembly Budget Subcommittee No. 5 on State Administration`. (You should be able tell by the URL of the link whether the committee is an Assembly or Senate committee; I would append the word `Committee` to the end of the name if and only if the string `committee` does not already appear in the name.

# Senate events

## Agenda items: events with only a "SUBJECT"

Seems to be same issue as Assembly, for example the Feb 7 JOINT HEARING SENATE EDUCATION AND ASSEMBLY HIGHER EDUCATION event should have an agenda item of "The State of Public Higher Education Coordination and                   Collaboration" instead of "INFORMATIONAL HEARING"

image

**Comment by jessemortenson** [comment]
Oh, I forgot to mention! I did have to make a few tweaks to get the script to run all the way through. I didn't push a commit, but I can if you want me to. Here's the diff:

```diff
diff --git a/scrapers/ca/events_web.py b/scrapers/ca/events_web.py
index 237f8f7a0..21f42fad4 100644
--- a/scrapers/ca/events_web.py
+++ b/scrapers/ca/events_web.py
@@ -73,19 +73,23 @@ class CAEventWebScraper(Scraper, LXMLMixin):
                     if "p.m." in row or "a.m." in row or " - " in row
                 ]
                 time_loc = "".join(time_loc)
-                hearing_time, hearing_location = time_loc.split(" - ")
+                self.logger.warning(f"tim_loc split {time_loc.split(' - ')}")
+                # hearing_time, hearing_location = time_loc.split(" - ")
+                time_loc_parts = time_loc.split(" - ")
+                hearing_time = time_loc_parts[0]
                 hearing_time = (
                     hearing_time.replace(".", "").strip(strip_chars)
                     if ".m." in hearing_time
                     else ""
                 )
+                hearing_location = " ".join(time_loc_parts[1:None])
                 hearing_location = hearing_location.strip(strip_chars)
 
-                when = " ".join([hearing_date, hearing_time]).strip()
+                when = " ".join([hearing_date, hearing_time]).replace("or upon adjournment of Session", "").strip()
                 when = dateutil.parser.parse(when)
                 when = self._tz.localize(when)
 
-                status = "canceled" if "CANCEL" in panel_content else "confirmed"
+                status = "cancelled" if "CANCEL" in panel_content else "confirmed"
```

**Comment by braykuka** [comment]
@jessemortenson please review it.

**Comment by jessemortenson** [comment]
Hello, thanks for the revision. However right off the bat it looks like it's outputting a lot of duplicate events, for example here are all the individual events at the same start time of `2024-02-06T22:30:00+00:00`

```jesse@greenbookwork:~/repo/openstates/braykuka/openstates-scrapers/_data/ca$ for x in `rg -ci '"2024-02-06T22:30:00\+00:00"' event_*`; do cat `echo "$x" | awk -F':' '{print $1}'` | jq ._id,.name,.start_date,.location.name; done
"06405a72-c541-11ee-ae71-0242ac170002"
"BUDGET SUBCOMMITTEE NO. 6 ON PUBLIC SAFETY"
"2024-02-06T22:30:00+00:00"
"State Capitol, Room 437"
"063fc03a-c541-11ee-ae71-0242ac170002"
"BUDGET SUBCOMMITTEE NO. 1 ON HEALTH"
"2024-02-06T22:30:00+00:00"
"State Capitol, Room 127"
"06401f62-c541-11ee-ae71-0242ac170002"
"BUDGET SUBCOMMITTEE NO. 6 ON PUBLIC SAFETY"
"2024-02-06T22:30:00+00:00"
"State Capitol, Room 437"
"063ef15a-c541-11ee-ae71-0242ac170002"
"BUDGET SUBCOMMITTEE NO. 1 ON HEALTH"
"2024-02-06T22:30:00+00:00"
"State Capitol, Room 127"
"063e7748-c541-11ee-ae71-0242ac170002"
"JOINT HEARING BUDGET SUBCOMMITTEE NO. 1 ON HEALTH AND SUBCOMMITTEE NO. 3 ON EDUCATION FINANCE"
"2024-02-06T22:30:00+00:00"
"State Capitol, Room 127"
"063e1a96-c541-11ee-ae71-0242ac170002"
"BUDGET SUBCOMMITTEE NO. 1 ON HEALTH"
"2024-02-06T22:30:00+00:00"
"State Capitol, Room 127"
"063f58d4-c541-11ee-ae71-0242ac170002"
"BUDGET SUBCOMMITTEE NO. 1 ON HEALTH"
"2024-02-06T22:30:00+00:00"
"State Capitol, Room 127"
"063d760e-c541-11ee-ae71-0242ac170002"
"BUDGET SUBCOMMITTEE NO. 1 ON HEALTH"
"2024-02-06T22:30:00+00:00"
"State Capitol, Room 127"
"063cea54-c541-11ee-ae71-0242ac170002"
"BUDGET SUBCOMMITTEE NO. 1 ON HEALTH"
"2024-02-06T22:30:00+00:00"
"State Capitol, Room 127"
"063c0a26-c541-11ee-ae71-0242ac170002"
"BUDGET SUBCOMMITTEE NO. 1 ON HEALTH"
"2024-02-06T22:30:00+00:00"
"State Capitol, Room 127"
"063c7fe2-c541-11ee-ae71-0242ac170002"
"BUDGET SUBCOMMITTEE NO. 1 ON HEALTH"
"2024-02-06T22:30:00+00:00"
"State Capitol, Room 127"
```

In that list, you can see multiple events happening at the same time and the same location. In that list, I think there should only be 3 distinct events. So that may have been an overcorrection (previously too few events, now too many)

The command I ran to run the scraper is `docker compose run --rm ca-scrape ca events_web --scrape`

**Comment by braykuka** [comment]
@jessemortenson  fixed it.

**Pull request merged**
