### PR TITLE
VA: improve Senate/upper events scraper

### PR DESCRIPTION
**Pull request by braykuka**
openstates/issues [1145](https://github.com/openstates/issues/issues/1145)

### CODE REVIEW

**Comment by braykuka** [comment]
@jessemortenson Please review it.

**Comment by NewAgeAirbender** [comment]
Spot checks look pretty solid

**Comment by jessemortenson** [comment]
Thanks, Bray, and @NewAgeAirbender for checking. Did you get the full scrape to run? When I ran it I eventually got:

```
/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/bin/python -m openstates.cli.update --scrape --fastmode va events 
23:49:14 DEBUG openstates.stats: Stat emission is not enabled.
23:49:14 INFO root: Module: va
va (scrape)
  events: {}
23:49:15 INFO openstates: save jurisdiction Virginia as jurisdiction_ocd-jurisdiction-country:us-state:va-government.json
23:49:15 INFO openstates: save organization Virginia General Assembly as organization_2438604a-b9b3-11ee-8fe9-5f4f732bdcb2.json
23:49:15 INFO openstates: save organization Senate as organization_2438604b-b9b3-11ee-8fe9-5f4f732bdcb2.json
23:49:15 INFO openstates: save organization House as organization_2438604c-b9b3-11ee-8fe9-5f4f732bdcb2.json
/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py:101: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  "session" in inspect.getargspec(ScraperCls.scrape).args
23:49:15 WARNING openstates: no session provided, using active sessions: {'2024'}
23:49:15 INFO scrapelib: GET - 'https://virginiageneralassembly.gov/house/schedule/meetingSchedule.php?range=long'
... [ lines omitted ] ...
23:49:30 INFO openstates: save event 2024-03-07 06:30:00-05:00 Capitol Commission Bible Study as event_2c843a51-b9b3-11ee-8fe9-5f4f732bdcb2.json
23:49:30 INFO openstates: save event 2024-03-19 10:00:00-04:00 Virginia Israel Advisory Board as event_2c843a52-b9b3-11ee-8fe9-5f4f732bdcb2.json
23:49:30 INFO scrapelib: GET - 'https://lis.virginia.gov/cgi-bin/legp604.exe?241+oth+MTG&241+oth+MTG'
Traceback (most recent call last):
  File "/home/jesse/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jesse/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 551, in <module>
    sys.exit(main())
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 541, in main
    report = do_update(args, other, juris)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 337, in do_update
    report["scrape"] = do_scrape(juris, args, scrapers, active_sessions)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 124, in do_scrape
    partial_report = scraper.do_scrape(**scrape_args, session=session)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/scrape/base.py", line 233, in do_scrape
    for obj in self.scrape(**kwargs) or []:
  File "/home/jesse/repo/openstates/braykuka/openstates-scrapers/scrapers/va/events.py", line 23, in scrape
    yield from self.scrape_upper(session_id)
  File "/home/jesse/repo/openstates/braykuka/openstates-scrapers/scrapers/va/events.py", line 142, in scrape_upper
    when = dateutil.parser.parse(f"{date} {time}")
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: 01/23/24 None
```

I also did a few spot checks from the events returned prior to that error and overall looks really good. There is one small data bug I think could be fixed easily: an agenda item that is not actually a bill, but was encoded as a bill. The output JSON was:

```
"agenda": [
    {
      "description": "Presentation by Curtis G. Manchester, Senior Asst. Attorney General, Transportation & Construction Section Virginia Office of the Attorney General",
      "classification": [],
      "related_entities": [
        {
          "name": "Virginia Public Procurement Law",
          "entity_type": "bill",
          "note": "consideration",
          "bill_id": "~{\"identifier\": \"\\n\\t\\t\\t           Virginia Public Procurement Law              \"}"
        }
      ],
      "subjects": [],
      "media": [],
      "notes": [],
      "order": 0,
      "extras": {}
    },
```

Corresponding to this committee agenda: https://virginiageneralassembly.gov/house/agendas/agendaItem.php?id=4155

You could use a regex to test the string of the link to see if it matches a bill pattern. Every bill identifier in VA should be in the form `[A-Z][A-Z][0-9]+`, where the first two letters are one of these combinations: 

```
+---------+
|substring|
+---------+
|HB       |
|HJ       |
|HR       |
|SB       |
|SJ       |
|SR       |
+---------+
```

So something like `(HB|HJ|HR|SB|SJ|SR)[0-9]+` should work.

**Comment by braykuka** [comment]
Thanks for your feedback. I will check this issue.

**Comment by jessemortenson** [comment]
LGTM, merging in!

**Pull request merged**
