### PR TITLE
Don't change Massachusetts House district names

### PR DESCRIPTION
**Pull request by bhrutledge**
Fixes https://github.com/openstates/issues/issues/170.

This may be premature and and presumptuous, but it seemed liked a quick thing to do. I haven't tested it locally; happy to go through the [setup](https://docs.openstates.org/en/latest/contributing/scrapers.html) if requested.

### CODE REVIEW

**Comment by jamesturk** [comment]
👍 i'll pull this in, the actual change will take us doing this in openstates/people

**Comment by bhrutledge** [comment]
Thanks @jamesturk! Out of curiosity, can you point to where the parallel change needs to be made?

**Comment by jamesturk** [comment]
In the data itself here:
https://github.com/openstates/people/tree/main/data/ma

Doing so will avoid merge issues/etc.  when we do update MA legislators

**Comment by bhrutledge** [comment]
@jamesturk Gotcha. I see some instructions at https://docs.openstates.org/en/latest/contributing/people.html. Continuing with my curiosity, is this a regular/automated maintenance task? Does it warrant a separate issue and/or PR?

**Comment by jamesturk** [comment]
This change will have to be done manually to the old legislators,
essentially a find and replace across those YAML files.

**Pull request merged**
