### PR TITLE
PA: bills and events scraper rewrite 2025

### PR DESCRIPTION
**Pull request by braykuka**
Added bills and events scrapers for PA

- [1238](https://github.com/openstates/issues/issues/1238)
- [1239](https://github.com/openstates/issues/issues/1239)

### CODE REVIEW

**Comment by braykuka** [comment]
@jessemortenson 
I've added bills and events scrapers for PA. Please review them and let me know if you have issues.
Thanks.

**Comment by jessemortenson** [comment]
Thanks, Bray. Unfortunately I was sick the last couple days so I'm catching up. 

Also we had a community contributor who came in with a PR on the PA events scraper a little bit before your PR showed up (https://github.com/openstates/openstates-scrapers/pull/5054), so that complicates things a bit. We rarely have big contributions from community volunteers but we do want to encourage that :)

There are a few things that your version of the events scraper does better, though. And a few things that need fixing. Can you please refactor this PR to make the events scraper an improvement against current code (including the contributor's scraper)? 

Here's what I'm seeing with the events data output from your scraper:

- There are some events on the PA site that have the start time listed as `Call of Chair`. Your scraper gets these (and the other does not). That's good! But can we please:
    - set `all_day` to `True` for those events
    - when you pass the `start_date` value for these events, use the datetime object's `.date()` method to just pass pass a `datetime.date` object (since we don't have the actual time for the event)
- Something is wrong with the participant name logic, because I am seeing names with newline characters, whitespace, and multiple names all in one value. Here's an example:

image

- I think the times for these events are wrong. For example, the Center for Rural Pennsylvania event (10:00am, Wednesday, October 16) comes out in the scraped output as `"2024-10-16T04:00:00+00:00"`. I am expecting a [UTC value](https://www.timeanddate.com/worldclock/converter.html?iso=20241016T140000&p1=97&p2=1440) of `"2024-10-16T14:00:00+00:00"

image

Still need to review the bills scraper, I'll provide feedback on that next

**Comment by jessemortenson** [comment]
Taking a first look at PA bills rewrite: I got an error running the scraper. Can you please check that?

start of scrape:

```
/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/bin/python -m openstates.cli.update --scrape pa bills 
16:47:53 DEBUG openstates.stats: Stat emission is not enabled.
16:47:53 INFO root: Module: pa
pa (scrape)
  bills: {}
16:47:54 INFO openstates: save jurisdiction Pennsylvania as jurisdiction_ocd-jurisdiction-country:us-state:pa-government.json
16:47:54 INFO openstates: save organization Pennsylvania General Assembly as organization_4ca3a1ca-8c08-11ef-ad10-4c034f4dc15f.json
16:47:54 INFO openstates: save organization Senate as organization_4ca3a1cb-8c08-11ef-ad10-4c034f4dc15f.json
16:47:54 INFO openstates: save organization House as organization_4ca3a1cc-8c08-11ef-ad10-4c034f4dc15f.json
16:47:54 WARNING openstates: no session provided, using active sessions: {'2023-2024S1', '2023-2024'}
```

error later on:

```
17:23:25 INFO openstates: save vote_event 2023-2024 - 2024-09-16 00:00:00-04:00 - FINAL PASSAGE as vote_event_42ff44f8-8c0d-11ef-ad10-4c034f4dc15f.json
17:23:25 INFO openstates: save bill SB 667 in 2023-2024 as bill_40dfe560-8c0d-11ef-ad10-4c034f4dc15f.json
17:23:25 INFO scrapelib: GET - 'https://www.palegis.us/legislation/bills/2023/sb668'
17:23:28 INFO scrapelib: GET - 'https://www.palegis.us/legislation/amendments/amendment-list?searchby=amendment&sessyr=2023&sessind=0&billbody=s&billtype=b&billnum=668&billpn=1460'
17:23:29 INFO scrapelib: GET - 'https://www.palegis.us/senate?searchby=amendment&sessyr=2023&sessind=0&billbody=s&billtype=b&billnum=668&billpn=1180'
Traceback (most recent call last):
  File "/home/jesse/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jesse/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 610, in <module>
    sys.exit(main())
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 600, in main
    report = do_update(args, other, juris)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 389, in do_update
    report["scrape"] = do_scrape(juris, args, scrapers, active_sessions)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 133, in do_scrape
    partial_report = scraper.do_scrape(**scrape_args, session=session)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/scrape/base.py", line 236, in do_scrape
    for obj in self.scrape(**kwargs) or []:
  File "/home/jesse/repo/openstates/braykuka/openstates-scrapers/scrapers/pa/bills.py", line 27, in scrape
    yield from self.scrape_session(chamber, session)
  File "/home/jesse/repo/openstates/braykuka/openstates-scrapers/scrapers/pa/bills.py", line 37, in scrape_session
    yield from self.parse_bill(chamber, session, special, link)
  File "/home/jesse/repo/openstates/braykuka/openstates-scrapers/scrapers/pa/bills.py", line 73, in parse_bill
    self.parse_bill_versions(bill, page)
  File "/home/jesse/repo/openstates/braykuka/openstates-scrapers/scrapers/pa/bills.py", line 120, in parse_bill_versions
    self.scrape_amendments(bill, a.attrib["href"], "House")
  File "/home/jesse/repo/openstates/braykuka/openstates-scrapers/scrapers/pa/bills.py", line 158, in scrape_amendments
    version_name = row.xpath(
IndexError: list index out of range

Process finished with exit code 1
```

**Comment by braykuka** [comment]
Thank you for your review, @jessemortenson. I will check and fix them.

**Comment by braykuka** [comment]
@jessemortenson please review it.

**Comment by braykuka** [comment]
@jessemortenson sorry for that issue. I was able to run it fully on my localhost. I will check and fix it.

**Comment by jessemortenson** [comment]
Thanks for checking! I also reviewed the Events scraper output - that looks good now. So the events part is done IMO. I did push one change to get the all_day events receiving just a Date (instead of DateTime)

```
diff --git a/scrapers/pa/events.py b/scrapers/pa/events.py
index 671b79d7d..8090f1391 100644
--- a/scrapers/pa/events.py
+++ b/scrapers/pa/events.py
@@ -57,15 +57,16 @@ class PAEventScraper(Scraper):
 
             if all_day:
                 start_date = datetime.datetime.strptime(date_string, "%Y-%m-%d")
+                start_date = start_date.date()
             else:
-                start_date = datetime.datetime.strptime(
+                start_date = self._tz.localize(
                      datetime.datetime.strptime(
                         "{} {}".format(date_string, time_string), "%Y-%m-%d %I:%M %p"
-                    )
+                ))
 
             event = Event(
                 name=title,
                 description=description,
-                start_date=self._tz.localize(start_date),
+                start_date=start_date,
                 location_name=location,
                 all_day=all_day,
             )
```

**Comment by braykuka** [comment]
@jessemortenson I've fixed some issues and run it successfully. Please review it. Thanks.

**Comment by jessemortenson** [comment]
Thanks! Looks good to me, merging in.

**Pull request merged**
