### PR TITLE
MN: add senate votes scraping logic

### PR DESCRIPTION
**Pull request by braykuka**
## Description

I've added the vote scraping logic for MN Senate.

### CODE REVIEW

**Comment by jessemortenson** [comment]
Thanks! Quick overview of the code looks good. Running the scraper I did run into an error:

```
/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/bin/python -m openstates.cli.update --scrape --fastmode mn bills 
16:54:06 DEBUG openstates.stats: Stat emission is not enabled.
16:54:06 INFO root: Module: mn
mn (scrape)
  bills: {}
16:54:06 INFO openstates: save jurisdiction Minnesota as jurisdiction_ocd-jurisdiction-country:us-state:mn-government.json
16:54:06 INFO openstates: save organization Minnesota State Legislature as organization_26bc9084-b4c2-11ee-9257-795d8259e6fb.json
16:54:06 INFO openstates: save organization Senate as organization_26bc9085-b4c2-11ee-9257-795d8259e6fb.json
16:54:06 INFO openstates: save organization House as organization_26bc9086-b4c2-11ee-9257-795d8259e6fb.json
/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py:101: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  "session" in inspect.getargspec(ScraperCls.scrape).args
16:54:06 WARNING openstates: no session provided, using active sessions: {'2023-2024'}

... [ many lines omitted ] ...

17:04:19 INFO scrapelib: GET - 'https://www.senate.mn/api/journal/gotopage?page=8150&ls=93'
17:04:20 INFO scrapelib: GET - 'https://www.senate.mn/journals/2023-2024/20230515070.pdf'
Traceback (most recent call last):
  File "/home/jesse/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jesse/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 551, in <module>
    sys.exit(main())
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 541, in main
    report = do_update(args, other, juris)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 337, in do_update
    report["scrape"] = do_scrape(juris, args, scrapers, active_sessions)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 124, in do_scrape
    partial_report = scraper.do_scrape(**scrape_args, session=session)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/scrape/base.py", line 238, in do_scrape
    for iterobj in obj:
  File "/home/jesse/repo/openstates/braykuka/openstates-scrapers/scrapers/mn/bills.py", line 300, in get_bill_info
    bill, votes = self.extract_actions(bill, doc, chamber)
  File "/home/jesse/repo/openstates/braykuka/openstates-scrapers/scrapers/mn/bills.py", line 450, in extract_actions
    vote, page_number = self.extract_vote_from_action(
  File "/home/jesse/repo/openstates/braykuka/openstates-scrapers/scrapers/mn/bills.py", line 675, in extract_vote_from_action
    vote_element.xpath(".//a[@href]/@href")[0]
IndexError: list index out of range
```

**Comment by braykuka** [comment]
@jessemortenson I've fixed this issue. The issue was that there were some votes which hasn't URL.

**Comment by jessemortenson** [comment]
Despite the execution error above, I did get some vote events in output before execution halted. Here are observations from that.

It looks like there are a number of Vote Events that still do not have any voters (`votes` property is an empty list):

```
jesse@greenbookwork:~/repo/openstates/braykuka/openstates-scrapers/scrapers/_data/mn$ for x in `rg -c '"votes": \[\]'`; do cat `echo "$x" | awk -F':' '{print $1}'` | jq .bill_identifier; done
"SF 2819"
"SF 31"
"SF 2909"
"SF 667"
"SF 1362"
"SF 395"
"SF 12"
"SF 1955"
"SF 33"
"SF 2909"
"SF 1816"
"SF 2369"
"SF 1213"
"SF 1213"
"SF 1499"
"SF 2744"
"SF 2904"
"SF 2934"
```

Aside from that issue, I spot checked a couple vote events that do have individual voters/votes:

- [SF 1955](https://www.revisor.mn.gov/bills/bill.php?b=Senate&f=SF1955&ssn=0&y=2023): looks good except one of the votes is affected by the bug noted above
- [SF 3307](https://www.revisor.mn.gov/bills/bill.php?b=Senate&f=SF3307&ssn=0&y=2023): looks good

**Comment by jessemortenson** [comment]
Hi Bray, in addition to the data issues mentioned above, I re-ran the scraper (after seeing your comment belatedly), and this time ran into this error - are you running the scrape after making changes?

```
/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/bin/python -m openstates.cli.update --scrape --fastmode mn bills 
18:12:49 DEBUG openstates.stats: Stat emission is not enabled.
18:12:49 INFO root: Module: mn
mn (scrape)
  bills: {}
18:12:50 INFO openstates: save jurisdiction Minnesota as jurisdiction_ocd-jurisdiction-country:us-state:mn-government.json
18:12:50 INFO openstates: save organization Minnesota State Legislature as organization_268469ce-b4cd-11ee-9257-795d8259e6fb.json
18:12:50 INFO openstates: save organization Senate as organization_268469cf-b4cd-11ee-9257-795d8259e6fb.json
18:12:50 INFO openstates: save organization House as organization_268469d0-b4cd-11ee-9257-795d8259e6fb.json
/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py:101: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  "session" in inspect.getargspec(ScraperCls.scrape).args
18:12:50 WARNING openstates: no session provided, using active sessions: {'2023-2024'}

... [ many lines omitted ] ...

18:15:23 INFO scrapelib: GET - 'https://www.senate.mn/api/journal/gotopage?page=128&ls=93'
18:15:23 INFO scrapelib: GET - 'https://www.senate.mn/journals/2023-2024/2023011005.pdf'
Traceback (most recent call last):
  File "/home/jesse/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jesse/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 551, in <module>
    sys.exit(main())
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 541, in main
    report = do_update(args, other, juris)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 337, in do_update
    report["scrape"] = do_scrape(juris, args, scrapers, active_sessions)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 124, in do_scrape
    partial_report = scraper.do_scrape(**scrape_args, session=session)
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/openstates/scrape/base.py", line 238, in do_scrape
    for iterobj in obj:
  File "/home/jesse/repo/openstates/braykuka/openstates-scrapers/scrapers/mn/bills.py", line 300, in get_bill_info
    bill, votes = self.extract_actions(bill, doc, chamber)
  File "/home/jesse/repo/openstates/braykuka/openstates-scrapers/scrapers/mn/bills.py", line 450, in extract_actions
    vote, page_number = self.extract_vote_from_action(
  File "/home/jesse/repo/openstates/braykuka/openstates-scrapers/scrapers/mn/bills.py", line 706, in extract_vote_from_action
    page = doc[page_number - 1].get_text() + doc[page_number].get_text()
  File "/home/jesse/.cache/pypoetry/virtualenvs/openstates-scrapers-YBlM38KZ-py3.9/lib/python3.9/site-packages/fitz/fitz.py", line 5797, in __getitem__
    raise IndexError("page not in document")
IndexError: page not in document
```

**Comment by braykuka** [comment]
@jessemortenson Please review it.

**Comment by jessemortenson** [comment]
Looks good, thanks! I did find two bugs that were quicker to fix than to explain, ended doing a moderate refactor around action table processing.

- smaller bug: one case where a journal page string included a non-numeric character, that made the web request for the PDF fail
- the other bug is that we can't count on the order of actions tables on the page to tell us whether the action took place in the House or the Senate. The order is flipped depending on whether it is a house bill or a senate bill! I actually found this via your log message about "Inconsistent between vote number and length of voters", so that was helpful!

**Pull request merged**
