### PR TITLE
restore linting

### PR DESCRIPTION
**Pull request by jamesturk**
black & flake8 linting accidentally got disabled a couple of months ago

### CODE REVIEW

**Comment by jamesturk** [comment]
this is kind of a big one since it had been disabled for a while, it changes a bunch of event.py files too so I wanted to make sure this wouldn't create any major merge conflicts with upcoming work @showerst

**Comment by showerst** [comment]
Thanks for the h/u -- my bad on the linting, i'll try to get my pre-commit pipeline configured to the same config that OS uses so that we stop needing these larger passes.

**Comment by jamesturk** [comment]
sounds good, my bad on not noticing it was disabled

if you use `pre-commit install` most things should just work, let me know if it gives you any trouble

**Comment by jamesturk** [comment]
wanted to confirm, ok to merge or better to hold off?

**Comment by showerst** [comment]
Cool with me to merge, thanks!

**Pull request merged**
